/* AUTO-GENERATED by tools/gen_platform.py — DO NOT EDIT */
/* Board: stm32f401re  CPU: cortex-m4  Clock: 16000000Hz */
#pragma once
#include <stdint.h>

/* ── RCC ─────────────────────────────────────────────── */
#define PLATFORM_RCC_BASE         0x40023800UL
#define PLATFORM_RCC_AHB1ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x30))
#define PLATFORM_RCC_APB1ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x40))
#define PLATFORM_RCC_APB2ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x44))

/* ── Console UART ────────────────────────────────────── */
#define PLATFORM_UART_NAME        "usart2"
#define PLATFORM_UART_BASE        0x40004400UL
#define PLATFORM_UART_SR          (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x00))
#define PLATFORM_UART_DR          (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x04))
#define PLATFORM_UART_BRR_REG     (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x08))
#define PLATFORM_UART_CR1         (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x0C))
#define PLATFORM_UART_BRR_VAL     0x008BU
#define PLATFORM_UART_BAUD        115200U
#define PLATFORM_UART_RCC_APB1    (1u << 17)
#define PLATFORM_UART_RCC_APB2    0U

/* ── UART TX Pin ─────────────────────────────────────── */
#define PLATFORM_TX_PORT_BASE     0x40020000UL
#define PLATFORM_TX_PORT_MODER    (*(volatile uint32_t*)(PLATFORM_TX_PORT_BASE + 0x00))
#define PLATFORM_TX_PORT_AFR0     (*(volatile uint32_t*)(PLATFORM_TX_PORT_BASE + 0x20))
#define PLATFORM_TX_PIN           2U
#define PLATFORM_TX_AF            7U
#define PLATFORM_TX_RCC_AHB1      (1u << 0)

/* ── LED ─────────────────────────────────────────────── */
#define PLATFORM_LED_PORT_BASE    0x40020000UL
#define PLATFORM_LED_PORT_MODER   (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x00))
#define PLATFORM_LED_PORT_OTYPER  (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x04))
#define PLATFORM_LED_PORT_OSPEEDR (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x08))
#define PLATFORM_LED_PORT_PUPDR   (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x0C))
#define PLATFORM_LED_PORT_BSRR    (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x18))
#define PLATFORM_LED_PIN          5U
#define PLATFORM_LED_RCC_AHB1     (1u << 0)

/* ── Button ──────────────────────────────────────────── */
#define PLATFORM_BTN_PORT_BASE    0x40020800UL
#define PLATFORM_BTN_PORT_MODER   (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x00))
#define PLATFORM_BTN_PORT_PUPDR   (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x0C))
#define PLATFORM_BTN_PORT_IDR     (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x10))
#define PLATFORM_BTN_PIN          13U
#define PLATFORM_BTN_RCC_AHB1     (1u << 2)

/* ── SysTick ─────────────────────────────────────────── */
#define PLATFORM_SYSTICK_LOAD     15999U
#define PLATFORM_CPU_HZ           16000000UL
