#!/usr/bin/env python3
"""
gen_platform.py — Generate platform_config.h from board JSON.
Usage: python3 gen_platform.py <board.json> <output.h>
"""
import sys, json

UART_BASES = {
    "usart1": 0x40011000,
    "usart2": 0x40004400,
    "usart6": 0x40011400,
}
GPIO_BASES = {
    "gpioa": 0x40020000,
    "gpiob": 0x40020400,
    "gpioc": 0x40020800,
    "gpiod": 0x40020C00,
    "gpioe": 0x40021000,
    "gpioh": 0x40021C00,
}
RCC_BASE       = 0x40023800
AHB1ENR_OFFSET = 0x30
APB1ENR_OFFSET = 0x40
APB2ENR_OFFSET = 0x44

GPIO_AHB1_BIT  = {"gpioa":0,"gpiob":1,"gpioc":2,"gpiod":3,"gpioe":4,"gpioh":7}
UART_APB1_BIT  = {"usart2":17}
UART_APB2_BIT  = {"usart1":4,"usart6":5}
UART_AF        = {"usart1":7,"usart2":7,"usart6":8}

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <board.json> <output.h>")
    sys.exit(1)

with open(sys.argv[1]) as f:
    board = json.load(f)

p   = board['platform']
clk = board['clock']['hsi_hz']

uart_name = p['console_uart']
baud      = p['console_baud']
uart_base = int(board['peripherals'][uart_name]['base'], 16)
uart_af   = UART_AF.get(uart_name, 7)

tx_pin_key = f"{uart_name}_tx"
tx_info    = board['pins'].get(tx_pin_key, {"port":"gpioa","pin":2})
tx_port    = tx_info['port']
tx_pin     = tx_info['pin']
tx_base    = GPIO_BASES[tx_port]

led_port  = p['led']['port']
led_pin   = p['led']['pin']
led_base  = GPIO_BASES[led_port]

btn_port  = p['btn']['port']
btn_pin   = p['btn']['pin']
btn_base  = GPIO_BASES[btn_port]

systick_load  = round(clk / 1000 * p['systick_ms']) - 1
uart_apb1_bit = UART_APB1_BIT.get(uart_name, -1)
uart_apb2_bit = UART_APB2_BIT.get(uart_name, -1)
led_ahb1_bit  = GPIO_AHB1_BIT.get(led_port, 0)
btn_ahb1_bit  = GPIO_AHB1_BIT.get(btn_port, 0)
tx_ahb1_bit   = GPIO_AHB1_BIT.get(tx_port, 0)

lines = [
    "/* AUTO-GENERATED by tools/gen_platform.py — DO NOT EDIT */",
    f"/* Board: {board['board']}  CPU: {board['cpu']}  Clock: {clk}Hz */",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "/* ── RCC ─────────────────────────────────────────────── */",
    f"#define PLATFORM_RCC_BASE         0x{RCC_BASE:08X}UL",
    f"#define PLATFORM_RCC_AHB1ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x{AHB1ENR_OFFSET:02X}))",
    f"#define PLATFORM_RCC_APB1ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x{APB1ENR_OFFSET:02X}))",
    f"#define PLATFORM_RCC_APB2ENR      (*(volatile uint32_t*)(PLATFORM_RCC_BASE + 0x{APB2ENR_OFFSET:02X}))",
    "",
    "/* ── Console UART ────────────────────────────────────── */",
    f"#define PLATFORM_UART_NAME        \"{uart_name}\"",
    f"#define PLATFORM_UART_BASE        0x{uart_base:08X}UL",
    f"#define PLATFORM_UART_SR          (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x00))",
    f"#define PLATFORM_UART_DR          (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x04))",
    f"#define PLATFORM_UART_BRR_REG     (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x08))",
    f"#define PLATFORM_UART_CR1         (*(volatile uint32_t*)(PLATFORM_UART_BASE + 0x0C))",
    f"#define PLATFORM_UART_BRR_VAL     0x{round(clk/baud):04X}U",
    f"#define PLATFORM_UART_BAUD        {baud}U",
    f"#define PLATFORM_UART_RCC_APB1    {f'(1u << {uart_apb1_bit})' if uart_apb1_bit>=0 else '0U'}",
    f"#define PLATFORM_UART_RCC_APB2    {f'(1u << {uart_apb2_bit})' if uart_apb2_bit>=0 else '0U'}",
    "",
    "/* ── UART TX Pin ─────────────────────────────────────── */",
    f"#define PLATFORM_TX_PORT_BASE     0x{tx_base:08X}UL",
    f"#define PLATFORM_TX_PORT_MODER    (*(volatile uint32_t*)(PLATFORM_TX_PORT_BASE + 0x00))",
    f"#define PLATFORM_TX_PORT_AFR0     (*(volatile uint32_t*)(PLATFORM_TX_PORT_BASE + 0x20))",
    f"#define PLATFORM_TX_PIN           {tx_pin}U",
    f"#define PLATFORM_TX_AF            {uart_af}U",
    f"#define PLATFORM_TX_RCC_AHB1      (1u << {tx_ahb1_bit})",
    "",
    "/* ── LED ─────────────────────────────────────────────── */",
    f"#define PLATFORM_LED_PORT_BASE    0x{led_base:08X}UL",
    f"#define PLATFORM_LED_PORT_MODER   (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x00))",
    f"#define PLATFORM_LED_PORT_OTYPER  (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x04))",
    f"#define PLATFORM_LED_PORT_OSPEEDR (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x08))",
    f"#define PLATFORM_LED_PORT_PUPDR   (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x0C))",
    f"#define PLATFORM_LED_PORT_BSRR    (*(volatile uint32_t*)(PLATFORM_LED_PORT_BASE + 0x18))",
    f"#define PLATFORM_LED_PIN          {led_pin}U",
    f"#define PLATFORM_LED_RCC_AHB1     (1u << {led_ahb1_bit})",
    "",
    "/* ── Button ──────────────────────────────────────────── */",
    f"#define PLATFORM_BTN_PORT_BASE    0x{btn_base:08X}UL",
    f"#define PLATFORM_BTN_PORT_MODER   (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x00))",
    f"#define PLATFORM_BTN_PORT_PUPDR   (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x0C))",
    f"#define PLATFORM_BTN_PORT_IDR     (*(volatile uint32_t*)(PLATFORM_BTN_PORT_BASE + 0x10))",
    f"#define PLATFORM_BTN_PIN          {btn_pin}U",
    f"#define PLATFORM_BTN_RCC_AHB1     (1u << {btn_ahb1_bit})",
    "",
    "/* ── SysTick ─────────────────────────────────────────── */",
    f"#define PLATFORM_SYSTICK_LOAD     {systick_load}U",
    f"#define PLATFORM_CPU_HZ           {clk}UL",
]

with open(sys.argv[2], 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"[GEN ] platform_config.h generated from {sys.argv[1]}")
